
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORIAS_TAG CATEGORIA_TAG COMA COMILLAS CORCHETE_D CORCHETE_I CUADRO_D CUADRO_I DOS_PUNTOS FECHA FECHA_TAG NULL NUMERO NUMERO_SHOW_TAG PREGUNTAS_TAG PREGUNTA_TAG RESPUESTA_TAG RONDA_TAG STRING VALOR VALOR_TAGarchivo : CORCHETE_I categorias COMA preguntas CORCHETE_Dcategorias : COMILLAS CATEGORIAS_TAG COMILLAS DOS_PUNTOS CUADRO_I listaCategorias CUADRO_Dpreguntas : COMILLAS PREGUNTAS_TAG COMILLAS DOS_PUNTOS CUADRO_I listaPreguntas CUADRO_DlistaCategorias : itemCategoria COMA listaCategorias \n                       | itemCategoriaitemCategoria : COMILLAS STRING COMILLAS\n                      | COMILLAS NUMERO COMILLASlistaPreguntas : itemPregunta COMA listaPreguntas \n                    | itemPreguntaitemPregunta : CORCHETE_I categoria COMA fecha COMA pregunta COMA valor COMA respuesta COMA ronda COMA numeroShow CORCHETE_Dcategoria : COMILLAS CATEGORIA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLAS\n                  | COMILLAS CATEGORIA_TAG COMILLAS DOS_PUNTOS COMILLAS NUMERO COMILLASfecha : COMILLAS FECHA_TAG COMILLAS DOS_PUNTOS COMILLAS FECHA COMILLASpregunta : COMILLAS PREGUNTA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLASvalor : COMILLAS VALOR_TAG COMILLAS DOS_PUNTOS COMILLAS VALOR COMILLAS\n              | COMILLAS VALOR_TAG COMILLAS DOS_PUNTOS NULLrespuesta : COMILLAS RESPUESTA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLAS\n                  | COMILLAS RESPUESTA_TAG COMILLAS DOS_PUNTOS COMILLAS NUMERO COMILLASronda : COMILLAS RONDA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLASnumeroShow : COMILLAS NUMERO_SHOW_TAG COMILLAS DOS_PUNTOS COMILLAS NUMERO COMILLAS'
    
_lr_action_items = {'CORCHETE_I':([0,19,31,],[2,26,26,]),'$end':([1,10,],[0,-1,]),'COMILLAS':([2,5,6,11,14,20,21,23,26,35,36,40,41,42,47,48,49,50,51,58,59,60,61,67,68,69,70,77,78,79,80,87,88,89,90,95,96,99,],[4,8,9,13,16,27,28,16,33,38,39,44,45,46,53,54,55,56,57,63,64,65,66,72,73,74,76,82,83,84,85,91,92,93,94,97,98,100,]),'COMA':([3,18,22,25,27,28,32,37,43,52,56,57,62,66,71,75,76,85,86,93,94,98,],[5,23,-2,31,-6,-7,35,40,47,58,-11,-12,67,-13,77,-16,-14,-15,-10,-17,-18,-19,]),'CATEGORIAS_TAG':([4,],[6,]),'CORCHETE_D':([7,30,81,100,],[10,-3,86,-20,]),'PREGUNTAS_TAG':([8,],[11,]),'DOS_PUNTOS':([9,13,39,45,54,64,73,83,91,],[12,15,42,49,60,69,79,88,95,]),'CUADRO_I':([12,15,],[14,19,]),'STRING':([16,46,65,84,92,],[20,50,70,89,96,]),'NUMERO':([16,46,84,97,],[21,51,90,99,]),'CUADRO_D':([17,18,24,25,27,28,29,34,86,],[22,-5,30,-9,-6,-7,-4,-8,-10,]),'CATEGORIA_TAG':([33,],[36,]),'FECHA_TAG':([38,],[41,]),'PREGUNTA_TAG':([44,],[48,]),'VALOR_TAG':([53,],[59,]),'FECHA':([55,],[61,]),'RESPUESTA_TAG':([63,],[68,]),'NULL':([69,],[75,]),'RONDA_TAG':([72,],[78,]),'VALOR':([74,],[80,]),'NUMERO_SHOW_TAG':([82,],[87,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'archivo':([0,],[1,]),'categorias':([2,],[3,]),'preguntas':([5,],[7,]),'listaCategorias':([14,23,],[17,29,]),'itemCategoria':([14,23,],[18,18,]),'listaPreguntas':([19,31,],[24,34,]),'itemPregunta':([19,31,],[25,25,]),'categoria':([26,],[32,]),'fecha':([35,],[37,]),'pregunta':([40,],[43,]),'valor':([47,],[52,]),'respuesta':([58,],[62,]),'ronda':([67,],[71,]),'numeroShow':([77,],[81,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> archivo","S'",1,None,None,None),
  ('archivo -> CORCHETE_I categorias COMA preguntas CORCHETE_D','archivo',5,'p_archivo','sintaxRules.py',2),
  ('categorias -> COMILLAS CATEGORIAS_TAG COMILLAS DOS_PUNTOS CUADRO_I listaCategorias CUADRO_D','categorias',7,'p_categorias','sintaxRules.py',15),
  ('preguntas -> COMILLAS PREGUNTAS_TAG COMILLAS DOS_PUNTOS CUADRO_I listaPreguntas CUADRO_D','preguntas',7,'p_preguntas','sintaxRules.py',19),
  ('listaCategorias -> itemCategoria COMA listaCategorias','listaCategorias',3,'p_listaCategorias','sintaxRules.py',23),
  ('listaCategorias -> itemCategoria','listaCategorias',1,'p_listaCategorias','sintaxRules.py',24),
  ('itemCategoria -> COMILLAS STRING COMILLAS','itemCategoria',3,'p_itemCategoria','sintaxRules.py',33),
  ('itemCategoria -> COMILLAS NUMERO COMILLAS','itemCategoria',3,'p_itemCategoria','sintaxRules.py',34),
  ('listaPreguntas -> itemPregunta COMA listaPreguntas','listaPreguntas',3,'p_listaPreguntas','sintaxRules.py',38),
  ('listaPreguntas -> itemPregunta','listaPreguntas',1,'p_listaPreguntas','sintaxRules.py',39),
  ('itemPregunta -> CORCHETE_I categoria COMA fecha COMA pregunta COMA valor COMA respuesta COMA ronda COMA numeroShow CORCHETE_D','itemPregunta',15,'p_itemPregunta','sintaxRules.py',48),
  ('categoria -> COMILLAS CATEGORIA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLAS','categoria',7,'p_categoria','sintaxRules.py',52),
  ('categoria -> COMILLAS CATEGORIA_TAG COMILLAS DOS_PUNTOS COMILLAS NUMERO COMILLAS','categoria',7,'p_categoria','sintaxRules.py',53),
  ('fecha -> COMILLAS FECHA_TAG COMILLAS DOS_PUNTOS COMILLAS FECHA COMILLAS','fecha',7,'p_fecha','sintaxRules.py',57),
  ('pregunta -> COMILLAS PREGUNTA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLAS','pregunta',7,'p_pregunta','sintaxRules.py',61),
  ('valor -> COMILLAS VALOR_TAG COMILLAS DOS_PUNTOS COMILLAS VALOR COMILLAS','valor',7,'p_valor','sintaxRules.py',65),
  ('valor -> COMILLAS VALOR_TAG COMILLAS DOS_PUNTOS NULL','valor',5,'p_valor','sintaxRules.py',66),
  ('respuesta -> COMILLAS RESPUESTA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLAS','respuesta',7,'p_respuesta','sintaxRules.py',73),
  ('respuesta -> COMILLAS RESPUESTA_TAG COMILLAS DOS_PUNTOS COMILLAS NUMERO COMILLAS','respuesta',7,'p_respuesta','sintaxRules.py',74),
  ('ronda -> COMILLAS RONDA_TAG COMILLAS DOS_PUNTOS COMILLAS STRING COMILLAS','ronda',7,'p_ronda','sintaxRules.py',78),
  ('numeroShow -> COMILLAS NUMERO_SHOW_TAG COMILLAS DOS_PUNTOS COMILLAS NUMERO COMILLAS','numeroShow',7,'p_numeroShow','sintaxRules.py',82),
]
